### ISSUE TITLE
Using `some_type | None` syntax for type annotations causes error in python 3.11

### ISSUE THREAD

**Issue by PhilReinhold** [fastapi/typer#533]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import typer
from datetime import datetime
print(typer.__version__)

app = typer.Typer()

@app.command()
def f(x: datetime | None = None):
    print(x)

if __name__ == "__main__":
    app()
```

### Description

In python 3.10 this script runs as expected, but on 3.11 I get the following error

```
Traceback (most recent call last):
  File "/Users/pcrein/qdash/test.py", line 16, in <module>
    app()
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 364, in get_command
    click_command = get_command_from_info(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 577, in get_command_from_info
    ) = get_params_convertors_ctx_param_name_from_function(command_info.callback)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 553, in get_params_convertors_ctx_param_name_from_function
    click_param, convertor = get_click_param(param)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 844, in get_click_param
    parameter_type = get_click_type(
                     ^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 773, in get_click_type
    raise RuntimeError(f"Type not yet supported: {annotation}")  # pragma no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Type not yet supported: datetime.datetime | None
```

### Operating System

macOS

### Typer Version

0.7.0

### Python Version

3.11.0

### Additional Context

I believe the issue is that for some reason, `typing.get_type_hints` is no longer converting the `UnionType` into a `Union`. I would suggest as a fix that `get_click_param` use `typing.get_origin/get_args` instead of `__args__` and `__origin__` attributes.

**Comment by domef** [comment]
I'm having the same issue. Using `Union[type1, type2]` with `from typing import Union` leads to the same error.

**Comment by raminqaf** [comment]
@tiangolo, Any updates on this feature?

**Comment by johnthagen** [comment]
Related to

- #348

**Comment by pdonorio** [comment]
Hi and thanks a lot for this great library!

I've run into this issue as well. May someone provide some guidance on what should be fixed, 
in case someone would like to contribute to solve it?

**Comment by renardeinside** [comment]
I have the same issue with Python 3.10. Any advisory on how to fix this?

**Comment by johnthagen** [comment]
The workaround for now is to use `Union[]` or `Optional[]`.

**Comment by lucasgadams** [comment]
Switching from `str | None = None` to `Optional[str] = None` worked for me.

**Comment by toppk** [comment]
> Switching from `str | None = None` to `Optional[str] = None` worked for me.

That is a pretty good workaround, but for me it means that I have to configure my linters one way for modules that use typer and another way for the rest of the code.

**Comment by roganartu** [comment]
> > Switching from `str | None = None` to `Optional[str] = None` worked for me.
> 
> That is a pretty good workaround, but for me it means that I have to configure my linters one way for modules that use typer and another way for the rest of the code.

pyupgrade will respect type aliases, as will typer. It's unwieldy, but this means you can do the following without having to configure pyupgrade to keep runtime types:

```
OptionalStr = Optional[str]

main(
    foo: OptionalStr = typer.Argument(None),
) -> None:
    ...
```

**Comment by exislow** [comment]
It would be great to use `str | None` instead of `Optional[]`. @tiangolo: Any plans to implement this to support >= Python3.11?

**Comment by dolfandringa** [comment]
I am stuck between Typer not supporting the new python syntax with `|None=None`  and pyupgrade refusing to add an option to skip code for a specific line.  I guess I'll try this solution.....

> > > Switching from `str | None = None` to `Optional[str] = None` worked for me.
> > 
> > 
> > That is a pretty good workaround, but for me it means that I have to configure my linters one way for modules that use typer and another way for the rest of the code.
> 
> pyupgrade will respect type aliases, as will typer. It's unwieldy, but this means you can do the following without having to configure pyupgrade to keep runtime types:
> 
> ```
> OptionalStr = Optional[str]
> 
> main(
>     foo: OptionalStr = typer.Argument(None),
> ) -> None:
>     ...
> ```

**Comment by funkindy** [comment]
Any updates on this?

**Comment by johnthagen** [comment]
@funkindy Waiting for @tiangolo to have time to review the MRs listed here

- https://github.com/tiangolo/typer/issues/678#issuecomment-2090423535

**Comment by hongqn** [comment]
> @funkindy Waiting for @tiangolo to have time to review the MRs listed here
> 
> - https://github.com/tiangolo/typer/issues/678#issuecomment-2090423535

Obviously @tiangolo either has no time, or has no will.

**Comment by tiangolo** [comment]
Hello all! This should have been fixed by https://github.com/fastapi/typer/pull/548

It is now available in Typer `0.12.4` :rocket:

**Comment by tonjo** [comment]
> Hello all! Thanks for the feedback. ☕
> 
> This should have been fixed by #548
> 
> It is now available in Typer `0.12.4` 🚀

Just upgraded to Typer 0.12.4 but still same error:

`TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'`

**Comment by tiangolo** [comment]
@tonjo please create a new discussion filling all the form data, including a minimal reproducible example we can copy and run to see your error.

Doing it with the original issue seems solved, so there's probably something different in your use case.

**Comment by pdonorio** [comment]
> > Hello all! Thanks for the feedback. ☕
> > This should have been fixed by #548
> > It is now available in Typer `0.12.4` 🚀
> 
> Just upgraded to Typer 0.12.4 but still same error:
> 
> `TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'`

Hey @tonjo have you created a new issue?

I'm getting the same issue if I try the operand inside "Annotated"

```python
app.command('some')
def some(
  option: Annotated[list | str, typer.Option()] = None,
):
   ...
```

In case I can open a new Issue if you didn't do it yet

**Comment by pypae** [comment]
@tonjo 
Are you on Python 3.10+? [Union type expressions were added in 3.10](https://docs.python.org/3/library/stdtypes.html#union-type).

If you're getting the following error, you're probably on an earlier version:

> `TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'`

--- 
@pdonorio 
I think there are two issues with your example:

- If I understand correctly, `typer` does still not support all Union types, only Optional `X | None` using the 3.10+ syntax. The wording in the release notes were not very clear about that.
- `list` cannot be used without a specific type for the list items. e.g. `list[str]`


```
app.command('some')
def some(
  option: Annotated[list | str, typer.Option()] = None,  # the following would work: option: Annotated[list[str] | None, typer.Option()] 
):
   ...
```

**Comment by pdonorio** [comment]
> * If I understand correctly, `typer` does still not support all Union types, only Optional `X | None` using the 3.10+ syntax. The wording in the release notes were not very clear about that.
> * `list` cannot be used without a specific type for the list items. e.g. `list[str]`

Thanks, using `list[str]` on the latest works @pypae 🙏

**Comment by tonjo** [comment]
@pypae  I'm using python 3.12.

Not using `typer` directly, though, it's an issue with `sqlmodel`, when defining an optional
field using a string (because that model is not defined yet), that error is thrown.

But maybe it is not the right place to comment to, as @tiangolo  suggested.

**Comment by NikosAlexandris** [comment]
``` bash
❯ python --version
Python 3.11.9
```
and
```
❯ ipython -c "import typer; print(typer.__version__)"
0.12.5
```
or indeed version 0.12.4 as well, I still get 

``` python
AssertionError: Typer Currently doesn't support Union types
```

Downgrading back to 0.12.3 complains then about 
```
RuntimeError: Type not yet supported: float | None
```

Though, I have more "unions", also in the form of `X | Y | None`.

**Comment by TiansuYu** [comment]
If I remember correctly, the `<type> | None` syntax is introduced in [3.10](https://peps.python.org/pep-0604/). Therefore Typer should test it against 3.10 as well IMO. But it seems that withTyper 0.12.5, I no longer has this issue any more.

**Comment by NikosAlexandris** [comment]
> ```shell
> ❯ python --version
> Python 3.11.9
> ```
> 
> and
> 
> ```
> ❯ ipython -c "import typer; print(typer.__version__)"
> 0.12.5
> ```
> 
> or indeed version 0.12.4 as well, I still get
> 
> ```python
> AssertionError: Typer Currently doesn't support Union types
> ```
> 
> Downgrading back to 0.12.3 complains then about
> 
> ```
> RuntimeError: Type not yet supported: float | None
> ```
> 
> Though, I have more "unions", also in the form of `X | Y | None`.

Indeed the problem here is more complex unions. I remove these for now and it works. But why not add support for it ?

**Comment by TiansuYu** [comment]
> Indeed the problem here is more complex unions. I removed these for now and it works. But why not add support for it ?

Indeed, i think Typer should support it (at least for all current python type annotations). In the future, i would hope that it supports all pydantic basemodel types as well.

**Comment by NikosAlexandris** [comment]
I think a "fix" would need to go around https://github.com/fastapi/typer/blob/master/typer/main.py#L844-L852.

**Comment by svlandeg** [comment]
Closing this issue as the original topic/problem has been addressed by https://github.com/fastapi/typer/pull/548. Thanks for all the discussion! If there are remaining/related issues, please open a new discussion thread - it's easier to have one specific topic per thread 🙏
